### ISSUE TITLE
Could not connect to ankiweb

### ISSUE THREAD

**Issue by bovine3dom** [damaru2/ankigenbot#11]
Hi, I'm getting 

```
Could not connect to ankiweb. Is your username and password correct? Check if you can access https://ankiweb.net/ with your credentials
```

when I try to add a word to a deck via telegram. It's the first time I've used the bot. I've set my username and password several times (admittedly at first it was actually wrong) and checked them thoroughly.

Can you confirm that the bot is still working for you?

Thanks : )

**Comment by damaru2** [comment]
It seems it's a problem from my side. My program has to crawl through the official website to push the information and maybe it changed. I'll fix it on Monday

**Comment by bovine3dom** [comment]
No rush! Have a good weekend : )

**Comment by damaru2** [comment]
Indeed, that was the issue, anki changed the web and now it doesn't allow to create a deck from it, it only allows to select one. I pushed a fix yesterday, it should be working now. Thanks for reporting

**Comment by bovine3dom** [comment]
Works great for me now, thanks for fixing it so quickly!
