### ISSUE TITLE
Please add Russian

### ISSUE THREAD

**Issue by timothy988** [damaru2/ankigenbot#12]
I love your bot could you please add Russian?

**Comment by damaru2** [comment]
I have no problem with adding any language as long as I have access to a free dictionary with the information. Unfortunately in the 21st century we still don't have easily available free public dictionaries that you can download in bulk and use. If you know any source from which I could obtain an English Russian dictionary I could try adding it

**Comment by timothy988** [comment]
Thanks for the reply I found this opensource dictionary. Is this any good

https://en.openrussian.org/dictionary

**Comment by damaru2** [comment]
It is not very good. For starters, it seems it is incomplete and has several mistakes, as they acknowledge. Secondly, it is a translation dictionary only. That is, it provides an English word for each Russian word. Translating one word by one word is often a way of learning words wrong (you might miss the nuances of the meaning of each word, and other things) once you go beyond of the easy common ones. This application focuses on sending you a definition of the word using the target language. That is, a what you could find in a regular dictionary for that language.

You might be lucky though, I think I have found a way to add Russian, I'll post here again when I look more into it.

**Comment by timothy988** [comment]
Thank you very much for your kind answer, I would be sohappy to see russian added
Thanks for all
