### ISSUE TITLE
Sqlite

### ISSUE THREAD

**Issue by timothy988** [damaru2/ankigenbot#13]
Hello,

When I write on telegram /start I receive the text "Write any word, select definitions and add them to anki!" When i type the word I receive this output on the terminal

sqlite3.OperationalError: unable to open database file

I have Ubuntu, when I write pip3 install sqlite3 I get on the terminal this text

ERROR: Could not find a version that satisfies the requirement sqlite3
ERROR: No matching distribution found for sqlite3

I have tried Installing pysqlite3 ans sudo apt install sqlite/sqlite3 and still not working.

Thank Indeed for your bot

**Comment by damaru2** [comment]
About the first thing, I guess you are doing it on https://t.me/ankigen_bot is that right?

**Comment by timothy988** [comment]
Solved the issue I did not have created the folder data and log in src, the guide said to create in the root not in the src or I might have read incorrectly
No I am doing my own server telegram bot. Because I would like to try to add Russian but it seems difficult for me to figur out how to do it.

**Comment by timothy988** [comment]
> About the first thing, I guess you are doing it on https://t.me/ankigen_bot is that right?

No I am doing on my own telegram python bot I was referring to my python bot, but now is all solved. I am trying to figure out how to add Russian but it seems impossible to me ahah
