### ISSUE TITLE
Bot stopped working

### ISSUE THREAD

**Issue by jagr21** [damaru2/ankigenbot#18]
Hello, since this morning the bot stopped working. It doesn't respond to words or commands. What could be the problem? Thank you.

**Comment by jagr21** [comment]
Working again!

**Comment by damaru2** [comment]
It was just a problem with the connection of the hosting service.

**Comment by jagr21** [comment]
Hey, since a couple of days ago the bot stopped responding, any idea what could be the problem?

**Comment by jagr21** [comment]
Working fine now.
