### ISSUE TITLE
card added to wrong deck

### ISSUE THREAD

**Issue by AriaMoradi** [damaru2/ankigenbot#2]
I generated a card and my deck name is set to "English all" but the card appeard on the default deck

**Comment by damaru2** [comment]
I can't reproduce your error. I did see that if you remove the deck from your client but you don't synchronize it with the cloud, then you add another card and synchronize Anki synchronization sees that you deleted the deck but there was a new card in that deck and it rdoesn't want you to lose it and adds it to (I think) the last active deck. However this is just how Anki synchronizes things. If after deleting the deck you synchronize there is no problem at all.

Please could you give me the steps you followed that lead to an error so I can try to reproduce them and fix them? It would be helpful to know if you already had a deck with that name (it shouldn't matter) if you deleted the deck, if not, if you synchronized things etc

**Comment by AriaMoradi** [comment]
If you have access to the database of the bot my username is aria.moradi007@gmail.com

**Comment by AriaMoradi** [comment]
Looks like the bot had problems first when I set my username and password...
![image](https://user-images.githubusercontent.com/8719233/39663383-cd8b2bdc-5087-11e8-99c1-6610e1e10440.png)
and Then I saw the word "have" was in the Default deck

I cant reproduce the error with any word even with 'have'

**Comment by damaru2** [comment]
Sorry I didn't get the last thing, are you saying you can't reproduce the error anymore and that only happened with the first word you tried?

**Comment by AriaMoradi** [comment]
oh sorry. there was a typo in there.
 and yes exactly what you said.

**Comment by damaru2** [comment]
I'll try to reproduce the error with a new user. I have no idea why this could happen.
