### ISSUE TITLE
Bot stopped working

### ISSUE THREAD

**Issue by colynxu** [damaru2/ankigenbot#21]
Hello, i can‘t add the word to my deck by using the bot. What could be the problem? Thank you.

**Comment by damaru2** [comment]
I'd need you to be more specific. The bot works, just add your credentials and the exact name of an existing deck (the latter wasn't needed until some months ago but now it is)

**Comment by colynxu** [comment]
<img width="385" alt="1651988844(1)" src="https://user-images.githubusercontent.com/13756509/167283631-1d7205dd-3eaf-44f2-819e-a5a1607ddd44.png">
like this， after i add my dxisting deck to the bot， it has no response。then i click the button “add to anki”， it still say “You need to specify the name of an existing deck with /deck”

**Comment by damaru2** [comment]
Hhmm are you a new user? I have identified a bug from the last update that makes the bot break for new users. It should be resolved now if you sent /start again

**Comment by colynxu** [comment]
ok,it's work!  Thanks~
