### ISSUE TITLE
Card fields wrong

### ISSUE THREAD

**Issue by dit7ya** [damaru2/ankigenbot#5]
I added my first card and the `back` got added to the `note ID` field.

Awesome idea and execution BTW.

**Comment by damaru2** [comment]
Mhhh... it could be because you have other kinds of deck types. I assumed (I don't know why) that the type that I use (Basic) was in the second position of the drop down list. I will fix it today or tomorrow

**Comment by damaru2** [comment]
I should be fixed now. Could you please try it and see if it works for you?

**Comment by dit7ya** [comment]
Yeah! I had to /swap the cards once and everything seems to work perfectly fine now!
Once again, thanks for creating this clever and useful project.
