### ISSUE TITLE
no definition

### ISSUE THREAD

**Issue by isotestardo** [damaru2/ankigenbot#6]
Hello,
I' m trying your bot right now. It seems to work with the command words, but when I insert a word, it doesn't provide any definition. Is it the bot still working? Am I missing something? I attach a screenshot. I'm using the last version of telegram on a Huawei P9 lite
![Screenshot_20190527-082356](https://user-images.githubusercontent.com/1021943/58399630-138d9000-8059-11e9-9425-d99a44d6b840.png)

**Comment by damaru2** [comment]
It works for me. I am seeing in the logs that there has been a problem but I cannot identify what. Can you paste your initial interaction with the bot (the settings, you don't need to paste username and password of course) and can you try to write another word so I can maybe trace back the problem? I have changed the information dumped to the logs in the place where I think the problem could be

**Comment by isotestardo** [comment]
Hello David,
I attached a screenshot of the initial interaction. After that I tried some
words and then I set up user,pass and deck.
I will try to insert another word in 10 minutes

https://i.ibb.co/0V9WfcZ/Screenshot-20190527-100708.png)

**Comment by damaru2** [comment]
Ok, I identified and fixed the problem. It turned out new users weren't able to register because of the last update, but it was working for old users. If you try to write /start again, it should work. Sorry for the inconvenience and thanks for reporting the problem!

**Comment by isotestardo** [comment]
It seems to work quite well now!! Thank you. Sometimes I get the message:

Could not connect to ankiweb. Is your username and password correct? Check if you can access https://ankiweb.net/ with your credentials

After some attempts it usually works.

**Comment by damaru2** [comment]
Yes, it's a know issue. I am not sure if it's anki's fault or mine. It is something I still have to investigate.I will close this issue since the original query has been solved

**Comment by isotestardo** [comment]
Now it works! thank you so much, you saved me a lot of time!

**Comment by isotestardo** [comment]
Thank you David!! Definitions seem to be working now , but it's not able to
add to anky. It says
'Could not connect to ankiweb. Is your username and password correct? Check
if you can access https://ankiweb.net/ with your credentials'
of course I've already set and checked credentials.

**Comment by damaru2** [comment]
Mmhh all the time? I thought you said it happened rather seldom, which is what happens to me. Have you set the deck name? Did the bot tell you it succeeded in getting your credentials when you add them?

**Comment by damaru2** [comment]
This is strange, unfortunately I won't be able to look at it until after the weekend. The bot may be inoperative until then

**Comment by isotestardo** [comment]
That's ok, it's working for me too!. I send a message  through the mail client, but probably it didn't work.

**Comment by isotestardo** [comment]
Ops, Actually it doesn't work at all at the moment, there 's no response for commands, words or even with the 'add to anki' of the previous definitions

**Comment by damaru2** [comment]
As I said, the bot may be inoperative until Monday.
