### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by Pristine-Maze** [damaru2/ankigenbot#9]
I started using ankigenbot last week and loved it. However, it stopped working yesterday. It does not respond to any word or command. Please see the attached screenshot. Could you check it out please? Thank you!
![image](https://user-images.githubusercontent.com/72515189/95358181-9d6c8080-087d-11eb-9fcb-153abb552e56.png)

**Comment by damaru2** [comment]
Oh, thanks for reporting this. It should be working now.

**Comment by Pristine-Maze** [comment]
Great. It works fine now. Thank you!

**Comment by damaru2** [comment]
No worries. Happy learning :))
